# path - .github/workflows/.yaml
name: Resuable Terraform  

on: 
  workflow_call:
  inputs:
    path:
      required: true
      type: string
jobs: 
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
        
      - name: Terraform Init
        run: terraform init -backend-config="backend.conf"
        working-directory: ${{ inputs.path }}

      - name: Terraform Plan
        run: aws s3 cp tfplan s3://tfplan-github/pre/-${{ input.path }}/tfplan-${{ github.sha }}
        working-directory: ${{ inputs.path }}