name: Terraform Destroy

on:
  workflow_dispatch:
    
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Check Files
        run: ls -la envs/pre

      - name: Configure AWS creds 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="backend.conf"
        working-directory: envs/pre

      - name: Terraform state list
        run: terraform state list
        working-directory: envs/pre

      - name: Terraform Destroy 
        run : terraform destroy 
        working-directory: envs/pre