name: Terraform Plan

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yaml'
      - 'terraform.tfvars'
      - '**/userdata.sh'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="envs/pre/backend.conf"
        working-directory: envs/pre

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: envs/pre

      - name: upload tfplan to s3
        run: aws s3 cp tfplan s3://tfplan-github/pre/-${{ github.sha }}
        working-directory: envs/pre

      - name: Show files in tfplan
        run : ls -la envs/pre

      - name: Show Plan
        run: terraform show -no-color tfplan
        working-directory: envs/pre
