name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Download Plan
        run: aws s3 cp s3://tfplan-github/pre/-${{ github.sha }} tfplan
        working-directory: envs/pre

      - name: Terraform Init
        run: terraform init -backend-config="envs/pre/backend.conf"
        working-directory: envs/pre

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: envs/pre
