name: Terraform Destroy

on:
  workflow_dispatch:
    
jobs:
  terraform-destroy:
    name: Terraform Destroy (Manual Approval)
    needs: terraform-apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS creds 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="envs/pre/backend.conf"
        working-directory: envs/pre

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with: 
          name: tfplan
          path: envs/pre

      - name: Terraform Destroy 
        run : terraform destroy tfplan
        working-directory: envs/pre