name: Terraform CICD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-plan:
    name: Terraform-Plan
    runs-on: ubuntu-latest
    outputs:
      plan-exists: ${{ steps.check-plan.outputs.exists }}
    
    steps:
      - name: Checout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version:  1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -backend-config="envs/pre/backend.conf"
        working-directory: envs/pre

      - name: Terraform Validate
        run: terraform validate
        working-directory: envs/pre

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: envs/pre
